---
- name: Install memcached
  yum:
    name: memcached
    state: latest
  tags:
  - memcached

- name: Config memcached
  template:
    src: memcached.jinja2
    dest: /etc/sysconfig/memcached
    mode: 0644
  tags:
  - memcached

- name: Enable memcached
  service:
    name: memcached
    state: restarted
    enabled: yes
  tags:
  - memcached